### Create new Movie
PATCH http://localhost:3200/movies/7d2832f8-c70a-410e-8963-4c93bf36cc9c
Content-Type: application/json

{
    "year": 2000,
    "title": "Esto es una prueba"
}

### Delete a movie

DELETE http://localhost:3200/movies/7d2832f8-c70a-410e-8963-4c93bf36cc9c
